# Databricks notebook source
# MAGIC %sql
# MAGIC CREATE TABLE DW_GOLD.GIT_SAMPLE_TABLE
# MAGIC (
# MAGIC VAL DECIMAL(20,2),
# MAGIC INT DECIMAL(20,2)
# MAGIC );
# MAGIC
# MAGIC
# MAGIC INSERT INTO DW_GOLD.GIT_SAMPLE_TABLE
# MAGIC SELECT  1, 1 
# MAGIC UNION ALL 
# MAGIC SELECT  2, 1
# MAGIC UNION ALL
# MAGIC SELECT  3, 3; 
